alter table public.equipes enable row level security;
alter table public.veiculos enable row level security;
alter table public.motoristas enable row level security;
alter table public.km_diario enable row level security;
alter table public.checklist enable row level security;
alter table public.checklist_fotos enable row level security;
alter table public.multas enable row level security;
alter table public.sinistros enable row level security;
alter table public.sinistro_fotos enable row level security;
alter table public.revisoes enable row level security;
alter table public.documentos_veiculo enable row level security;
alter table public.abastecimentos enable row level security;
alter table public.motorista_documentos enable row level security;
alter table public.veiculo_responsabilidade_historico enable row level security;
alter table public.centro_custo_historico enable row level security;
alter table public.pendencias enable row level security;

create policy "authenticated full access" on public.equipes for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.veiculos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.motoristas for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.km_diario for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.checklist for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.checklist_fotos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.multas for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.sinistros for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.sinistro_fotos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.revisoes for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.documentos_veiculo for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.abastecimentos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.motorista_documentos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.veiculo_responsabilidade_historico for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.centro_custo_historico for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.pendencias for all to authenticated using (true) with check (true);
